<?php require __DIR__ . '/lib/content.php'; $PAGE = 'privacy'; ?>
<?php require __DIR__ . '/lib/head.php'; ?>

<section class="section legal-page">
  <div class="container legal-page__inner">
    <h1 data-edit="legal.privacy.heading"><?= e(c('legal.privacy.heading', 'Privacy Policy')) ?></h1>
    <p class="legal-page__updated">Last updated: <span data-edit="legal.privacy.updated"><?= e(c('legal.privacy.updated', 'January 2026')) ?></span></p>
    <div class="legal-page__notice">This is placeholder legal text generated by the site template — replace it with your own policy or have an attorney review it before publishing.</div>
    <?php foreach (c('legal.privacy.paragraphs', []) as $i => $para): ?>
    <p data-edit="legal.privacy.paragraphs.<?= $i ?>"><?= e($para) ?></p>
    <?php endforeach; ?>
  </div>
</section>

<?php require __DIR__ . '/lib/foot.php'; ?>
